const program = {
    name:"name",
	description:"descritpion",
	difficultylevel:"level",
    day1:[{name:"name"},
        {exercise1:"name",descritpion:"desc"},
        {exercise2:"name",descritpion:"desc"},
        {exercise3:"name",descritpion:"desc"},
        {exercise4:"name",descritpion:"desc"},
        {exercise5:"name",descritpion:"desc"},
        {exercise6:"name",descritpion:"desc"},
    ],
    day2:[{name:"name"},
        {exercise1:"name",descritpion:"desc"},
        {exercise2:"name",descritpion:"desc"},
        {exercise3:"name",descritpion:"desc"},
        {exercise4:"name",descritpion:"desc"},
        {exercise5:"name",descritpion:"desc"},
        {exercise6:"name",descritpion:"desc"},
    ],
    day3:[{name:"name"},
        {exercise1:"name",descritpion:"desc"},
        {exercise2:"name",descritpion:"desc"},
        {exercise3:"name",descritpion:"desc"},
        {exercise4:"name",descritpion:"desc"},
        {exercise5:"name",descritpion:"desc"},
        {exercise6:"name",descritpion:"desc"},
    ],
    day4:[{name:"name"},
        {exercise1:"name",descritpion:"desc"},
        {exercise2:"name",descritpion:"desc"},
        {exercise3:"name",descritpion:"desc"},
        {exercise4:"name",descritpion:"desc"},
        {exercise5:"name",descritpion:"desc"},
        {exercise6:"name",descritpion:"desc"},
    ],
    day5:[{name:"name"},
        {exercise1:"name",descritpion:"desc"},
        {exercise2:"name",descritpion:"desc"},
        {exercise3:"name",descritpion:"desc"},
        {exercise4:"name",descritpion:"desc"},
        {exercise5:"name",descritpion:"desc"},
        {exercise6:"name",descritpion:"desc"},
    ],
    day6:[{name:"name"},
        {exercise1:"name",descritpion:"desc"},
        {exercise2:"name",descritpion:"desc"},
        {exercise3:"name",descritpion:"desc"},
        {exercise4:"name",descritpion:"desc"},
        {exercise5:"name",descritpion:"desc"},
        {exercise6:"name",descritpion:"desc"},
    ]


}





